# Baseic connection settings
listen_addresses = '*'
port = 5432

# WAL & Streaming Replication settings
# The 'WAL' it s Write Ahead Log, 
# which is used for replication and crash recovery. The following settings are recommended for a streaming replication setup.

wal_level = replica
max_wal_senders = 10
max_replication_slots = 10
wal_keep_size = 1GB
hot_standby = on

# Zero Data Loss configuration
synchronous_commit = on
synchronous_standby_names = 'ANY 1 (*)'
